#ifndef EUH_INIT_KEYMAPS_INC
#define EUH_INIT_KEYMAPS_INC

	// number keys //
	// SDLK_0
	lua_pushliteral(L,"0");
	lua_pushinteger(L,SDLK_0);
	lua_rawset(L,-3);
	lua_pushliteral(L,"0");
	lua_rawseti(L,-3,SDLK_0);
	// SDLK_1
	lua_pushliteral(L,"1");
	lua_pushinteger(L,SDLK_1);
	lua_rawset(L,-3);
	lua_pushliteral(L,"1");
	lua_rawseti(L,-3,SDLK_1);
	// SDLK_2
	lua_pushliteral(L,"2");
	lua_pushinteger(L,SDLK_2);
	lua_rawset(L,-3);
	lua_pushliteral(L,"2");
	lua_rawseti(L,-3,SDLK_2);
	// SDLK_3
	lua_pushliteral(L,"3");
	lua_pushinteger(L,SDLK_3);
	lua_rawset(L,-3);
	lua_pushliteral(L,"3");
	lua_rawseti(L,-3,SDLK_3);
	// SDLK_4
	lua_pushliteral(L,"4");
	lua_pushinteger(L,SDLK_4);
	lua_rawset(L,-3);
	lua_pushliteral(L,"4");
	lua_rawseti(L,-3,SDLK_4);
	// SDLK_5
	lua_pushliteral(L,"5");
	lua_pushinteger(L,SDLK_5);
	lua_rawset(L,-3);
	lua_pushliteral(L,"5");
	lua_rawseti(L,-3,SDLK_5);
	// SDLK_6
	lua_pushliteral(L,"6");
	lua_pushinteger(L,SDLK_6);
	lua_rawset(L,-3);
	lua_pushliteral(L,"6");
	lua_rawseti(L,-3,SDLK_6);
	// SDLK_7
	lua_pushliteral(L,"7");
	lua_pushinteger(L,SDLK_7);
	lua_rawset(L,-3);
	lua_pushliteral(L,"7");
	lua_rawseti(L,-3,SDLK_7);
	// SDLK_8
	lua_pushliteral(L,"8");
	lua_pushinteger(L,SDLK_8);
	lua_rawset(L,-3);
	lua_pushliteral(L,"8");
	lua_rawseti(L,-3,SDLK_8);
	// SDLK_9
	lua_pushliteral(L,"9");
	lua_pushinteger(L,SDLK_9);
	lua_rawset(L,-3);
	lua_pushliteral(L,"9");
	lua_rawseti(L,-3,SDLK_9);

	// letters //
	// SDLK_a
	lua_pushliteral(L,"a");
	lua_pushinteger(L,SDLK_a);
	lua_rawset(L,-3);
	lua_pushliteral(L,"a");
	lua_rawseti(L,-3,SDLK_a);
	// SDLK_b
	lua_pushliteral(L,"b");
	lua_pushinteger(L,SDLK_b);
	lua_rawset(L,-3);
	lua_pushliteral(L,"b");
	lua_rawseti(L,-3,SDLK_b);
	// SDLK_c
	lua_pushliteral(L,"c");
	lua_pushinteger(L,SDLK_c);
	lua_rawset(L,-3);
	lua_pushliteral(L,"c");
	lua_rawseti(L,-3,SDLK_c);
	// SDLK_d
	lua_pushliteral(L,"d");
	lua_pushinteger(L,SDLK_d);
	lua_rawset(L,-3);
	lua_pushliteral(L,"d");
	lua_rawseti(L,-3,SDLK_d);
	// SDLK_e
	lua_pushliteral(L,"e");
	lua_pushinteger(L,SDLK_e);
	lua_rawset(L,-3);
	lua_pushliteral(L,"e");
	lua_rawseti(L,-3,SDLK_e);
	// SDLK_f
	lua_pushliteral(L,"f");
	lua_pushinteger(L,SDLK_f);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f");
	lua_rawseti(L,-3,SDLK_f);
	// SDLK_g
	lua_pushliteral(L,"g");
	lua_pushinteger(L,SDLK_g);
	lua_rawset(L,-3);
	lua_pushliteral(L,"g");
	lua_rawseti(L,-3,SDLK_g);
	// SDLK_h
	lua_pushliteral(L,"h");
	lua_pushinteger(L,SDLK_h);
	lua_rawset(L,-3);
	lua_pushliteral(L,"h");
	lua_rawseti(L,-3,SDLK_h);
	// SDLK_i
	lua_pushliteral(L,"i");
	lua_pushinteger(L,SDLK_i);
	lua_rawset(L,-3);
	lua_pushliteral(L,"i");
	lua_rawseti(L,-3,SDLK_i);
	// SDLK_j
	lua_pushliteral(L,"j");
	lua_pushinteger(L,SDLK_j);
	lua_rawset(L,-3);
	lua_pushliteral(L,"j");
	lua_rawseti(L,-3,SDLK_j);
	// SDLK_k
	lua_pushliteral(L,"k");
	lua_pushinteger(L,SDLK_k);
	lua_rawset(L,-3);
	lua_pushliteral(L,"k");
	lua_rawseti(L,-3,SDLK_k);
	// SDLK_l
	lua_pushliteral(L,"l");
	lua_pushinteger(L,SDLK_l);
	lua_rawset(L,-3);
	lua_pushliteral(L,"l");
	lua_rawseti(L,-3,SDLK_l);
	// SDLK_m
	lua_pushliteral(L,"m");
	lua_pushinteger(L,SDLK_m);
	lua_rawset(L,-3);
	lua_pushliteral(L,"m");
	lua_rawseti(L,-3,SDLK_m);
	// SDLK_n
	lua_pushliteral(L,"n");
	lua_pushinteger(L,SDLK_n);
	lua_rawset(L,-3);
	lua_pushliteral(L,"n");
	lua_rawseti(L,-3,SDLK_n);
	// SDLK_o
	lua_pushliteral(L,"o");
	lua_pushinteger(L,SDLK_o);
	lua_rawset(L,-3);
	lua_pushliteral(L,"o");
	lua_rawseti(L,-3,SDLK_o);
	// SDLK_p
	lua_pushliteral(L,"p");
	lua_pushinteger(L,SDLK_p);
	lua_rawset(L,-3);
	lua_pushliteral(L,"p");
	lua_rawseti(L,-3,SDLK_p);
	// SDLK_q
	lua_pushliteral(L,"q");
	lua_pushinteger(L,SDLK_q);
	lua_rawset(L,-3);
	lua_pushliteral(L,"q");
	lua_rawseti(L,-3,SDLK_q);
	// SDLK_r
	lua_pushliteral(L,"r");
	lua_pushinteger(L,SDLK_r);
	lua_rawset(L,-3);
	lua_pushliteral(L,"r");
	lua_rawseti(L,-3,SDLK_r);
	// SDLK_s
	lua_pushliteral(L,"s");
	lua_pushinteger(L,SDLK_s);
	lua_rawset(L,-3);
	lua_pushliteral(L,"s");
	lua_rawseti(L,-3,SDLK_s);
	// SDLK_t
	lua_pushliteral(L,"t");
	lua_pushinteger(L,SDLK_t);
	lua_rawset(L,-3);
	lua_pushliteral(L,"t");
	lua_rawseti(L,-3,SDLK_t);
	// SDLK_u
	lua_pushliteral(L,"u");
	lua_pushinteger(L,SDLK_u);
	lua_rawset(L,-3);
	lua_pushliteral(L,"u");
	lua_rawseti(L,-3,SDLK_u);
	// SDLK_v
	lua_pushliteral(L,"v");
	lua_pushinteger(L,SDLK_v);
	lua_rawset(L,-3);
	lua_pushliteral(L,"v");
	lua_rawseti(L,-3,SDLK_v);
	// SDLK_w
	lua_pushliteral(L,"w");
	lua_pushinteger(L,SDLK_w);
	lua_rawset(L,-3);
	lua_pushliteral(L,"w");
	lua_rawseti(L,-3,SDLK_w);
	// SDLK_x
	lua_pushliteral(L,"x");
	lua_pushinteger(L,SDLK_x);
	lua_rawset(L,-3);
	lua_pushliteral(L,"x");
	lua_rawseti(L,-3,SDLK_x);
	// SDLK_y
	lua_pushliteral(L,"y");
	lua_pushinteger(L,SDLK_y);
	lua_rawset(L,-3);
	lua_pushliteral(L,"y");
	lua_rawseti(L,-3,SDLK_y);
	// SDLK_z
	lua_pushliteral(L,"z");
	lua_pushinteger(L,SDLK_z);
	lua_rawset(L,-3);
	lua_pushliteral(L,"z");
	lua_rawseti(L,-3,SDLK_z);

	// F keys //
	// SDLK_F1
	lua_pushliteral(L,"f1");
	lua_pushinteger(L,SDLK_F1);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f1");
	lua_rawseti(L,-3,SDLK_F1);
	// SDLK_F2
	lua_pushliteral(L,"f2");
	lua_pushinteger(L,SDLK_F2);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f2");
	lua_rawseti(L,-3,SDLK_F2);
	// SDLK_F3
	lua_pushliteral(L,"f3");
	lua_pushinteger(L,SDLK_F3);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f3");
	lua_rawseti(L,-3,SDLK_F3);
	// SDLK_F4
	lua_pushliteral(L,"f4");
	lua_pushinteger(L,SDLK_F4);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f4");
	lua_rawseti(L,-3,SDLK_F4);
	// SDLK_F5
	lua_pushliteral(L,"f5");
	lua_pushinteger(L,SDLK_F5);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f5");
	lua_rawseti(L,-3,SDLK_F5);
	// SDLK_F6
	lua_pushliteral(L,"f6");
	lua_pushinteger(L,SDLK_F6);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f6");
	lua_rawseti(L,-3,SDLK_F6);
	// SDLK_F7
	lua_pushliteral(L,"f7");
	lua_pushinteger(L,SDLK_F7);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f7");
	lua_rawseti(L,-3,SDLK_F7);
	// SDLK_F8
	lua_pushliteral(L,"f8");
	lua_pushinteger(L,SDLK_F8);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f8");
	lua_rawseti(L,-3,SDLK_F8);
	// SDLK_F9
	lua_pushliteral(L,"f9");
	lua_pushinteger(L,SDLK_F9);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f9");
	lua_rawseti(L,-3,SDLK_F9);
	// SDLK_F10
	lua_pushliteral(L,"f10");
	lua_pushinteger(L,SDLK_F10);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f10");
	lua_rawseti(L,-3,SDLK_F10);
	// SDLK_F11
	lua_pushliteral(L,"f11");
	lua_pushinteger(L,SDLK_F11);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f11");
	lua_rawseti(L,-3,SDLK_F11);
	// SDLK_F12
	lua_pushliteral(L,"f12");
	lua_pushinteger(L,SDLK_F12);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f12");
	lua_rawseti(L,-3,SDLK_F12);
	// SDLK_F13
	lua_pushliteral(L,"f13");
	lua_pushinteger(L,SDLK_F13);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f13");
	lua_rawseti(L,-3,SDLK_F13);
	// SDLK_F14
	lua_pushliteral(L,"f14");
	lua_pushinteger(L,SDLK_F14);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f14");
	lua_rawseti(L,-3,SDLK_F14);
	// SDLK_F15
	lua_pushliteral(L,"f15");
	lua_pushinteger(L,SDLK_F15);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f15");
	lua_rawseti(L,-3,SDLK_F15);
	// SDLK_F16
	lua_pushliteral(L,"f16");
	lua_pushinteger(L,SDLK_F16);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f16");
	lua_rawseti(L,-3,SDLK_F16);
	// SDLK_F17
	lua_pushliteral(L,"f17");
	lua_pushinteger(L,SDLK_F17);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f17");
	lua_rawseti(L,-3,SDLK_F17);
	// SDLK_F18
	lua_pushliteral(L,"f18");
	lua_pushinteger(L,SDLK_F18);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f18");
	lua_rawseti(L,-3,SDLK_F18);
	// SDLK_F19
	lua_pushliteral(L,"f19");
	lua_pushinteger(L,SDLK_F19);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f19");
	lua_rawseti(L,-3,SDLK_F19);
	// SDLK_F20
	lua_pushliteral(L,"f20");
	lua_pushinteger(L,SDLK_F20);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f20");
	lua_rawseti(L,-3,SDLK_F20);
	// SDLK_F21
	lua_pushliteral(L,"f21");
	lua_pushinteger(L,SDLK_F21);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f21");
	lua_rawseti(L,-3,SDLK_F21);
	// SDLK_F22
	lua_pushliteral(L,"f22");
	lua_pushinteger(L,SDLK_F22);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f22");
	lua_rawseti(L,-3,SDLK_F22);
	// SDLK_F23
	lua_pushliteral(L,"f23");
	lua_pushinteger(L,SDLK_F23);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f23");
	lua_rawseti(L,-3,SDLK_F23);
	// SDLK_F24
	lua_pushliteral(L,"f24");
	lua_pushinteger(L,SDLK_F24);
	lua_rawset(L,-3);
	lua_pushliteral(L,"f24");
	lua_rawseti(L,-3,SDLK_F24);

	// KP numbers //
	// SDLK_KP_0
	lua_pushliteral(L,"kp0");
	lua_pushinteger(L,SDLK_KP_0);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp0");
	lua_rawseti(L,-3,SDLK_KP_0);
	// SDLK_KP_1
	lua_pushliteral(L,"kp1");
	lua_pushinteger(L,SDLK_KP_1);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp1");
	lua_rawseti(L,-3,SDLK_KP_1);
	// SDLK_KP_2
	lua_pushliteral(L,"kp2");
	lua_pushinteger(L,SDLK_KP_2);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp2");
	lua_rawseti(L,-3,SDLK_KP_2);
	// SDLK_KP_3
	lua_pushliteral(L,"kp3");
	lua_pushinteger(L,SDLK_KP_3);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp3");
	lua_rawseti(L,-3,SDLK_KP_3);
	// SDLK_KP_4
	lua_pushliteral(L,"kp4");
	lua_pushinteger(L,SDLK_KP_4);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp4");
	lua_rawseti(L,-3,SDLK_KP_4);
	// SDLK_KP_5
	lua_pushliteral(L,"kp5");
	lua_pushinteger(L,SDLK_KP_5);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp5");
	lua_rawseti(L,-3,SDLK_KP_5);
	// SDLK_KP_6
	lua_pushliteral(L,"kp6");
	lua_pushinteger(L,SDLK_KP_6);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp6");
	lua_rawseti(L,-3,SDLK_KP_6);
	// SDLK_KP_7
	lua_pushliteral(L,"kp7");
	lua_pushinteger(L,SDLK_KP_7);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp7");
	lua_rawseti(L,-3,SDLK_KP_7);
	// SDLK_KP_8
	lua_pushliteral(L,"kp8");
	lua_pushinteger(L,SDLK_KP_8);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp8");
	lua_rawseti(L,-3,SDLK_KP_8);
	// SDLK_KP_9
	lua_pushliteral(L,"kp9");
	lua_pushinteger(L,SDLK_KP_9);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp9");
	lua_rawseti(L,-3,SDLK_KP_9);

	// KP symbols //
	// SDLK_KP_COMMA
	lua_pushliteral(L,"kp,");
	lua_pushinteger(L,SDLK_KP_COMMA);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp,");
	lua_rawseti(L,-3,SDLK_KP_COMMA);
	// SDLK_KP_DECIMAL
	lua_pushliteral(L,"kp.");
	lua_pushinteger(L,SDLK_KP_DECIMAL);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp.");
	lua_rawseti(L,-3,SDLK_KP_DECIMAL);
	// SDLK_KP_DIVIDE
	lua_pushliteral(L,"kp/");
	lua_pushinteger(L,SDLK_KP_DIVIDE);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp/");
	lua_rawseti(L,-3,SDLK_KP_DIVIDE);
	// SDLK_KP_ENTER
	lua_pushliteral(L,"kpenter");
	lua_pushinteger(L,SDLK_KP_ENTER);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kpenter");
	lua_rawseti(L,-3,SDLK_KP_ENTER);
	// SDLK_KP_EQUALS
	lua_pushliteral(L,"kp=");
	lua_pushinteger(L,SDLK_KP_EQUALS);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp=");
	lua_rawseti(L,-3,SDLK_KP_EQUALS);
	// SDLK_KP_MINUS
	lua_pushliteral(L,"kp-");
	lua_pushinteger(L,SDLK_KP_MINUS);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp-");
	lua_rawseti(L,-3,SDLK_KP_MINUS);
	// SDLK_KP_MULTIPLY
	lua_pushliteral(L,"kp*");
	lua_pushinteger(L,SDLK_KP_MULTIPLY);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp*");
	lua_rawseti(L,-3,SDLK_KP_MULTIPLY);
	// SDLK_KP_PLUS
	lua_pushliteral(L,"kp+");
	lua_pushinteger(L,SDLK_KP_PLUS);
	lua_rawset(L,-3);
	lua_pushliteral(L,"kp+");
	lua_rawseti(L,-3,SDLK_KP_PLUS);

	// symbol keys //
	// SDLK_SPACE
	lua_pushliteral(L,"space");
	lua_pushinteger(L,SDLK_SPACE);
	lua_rawset(L,-3);
	lua_pushliteral(L,"space");
	lua_rawseti(L,-3,SDLK_SPACE);
	// SDLK_AMPERSAND
	lua_pushliteral(L,"&");
	lua_pushinteger(L,SDLK_AMPERSAND);
	lua_rawset(L,-3);
	lua_pushliteral(L,"&");
	lua_rawseti(L,-3,SDLK_AMPERSAND);
	// SDLK_ASTERISK
	lua_pushliteral(L,"*");
	lua_pushinteger(L,SDLK_ASTERISK);
	lua_rawset(L,-3);
	lua_pushliteral(L,"*");
	lua_rawseti(L,-3,SDLK_ASTERISK);
	// SDLK_AT
	lua_pushliteral(L,"@");
	lua_pushinteger(L,SDLK_AT);
	lua_rawset(L,-3);
	lua_pushliteral(L,"@");
	lua_rawseti(L,-3,SDLK_AT);
	// SDLK_BACKSLASH
	lua_pushliteral(L,"\\");
	lua_pushinteger(L,SDLK_BACKSLASH);
	lua_rawset(L,-3);
	lua_pushliteral(L,"\\");
	lua_rawseti(L,-3,SDLK_BACKSLASH);
	// SDLK_BACKQUOTE
	lua_pushliteral(L,"`");
	lua_pushinteger(L,SDLK_BACKQUOTE);
	lua_rawset(L,-3);
	lua_pushliteral(L,"`");
	lua_rawseti(L,-3,SDLK_BACKQUOTE);
	// SDLK_CARET
	lua_pushliteral(L,"^");
	lua_pushinteger(L,SDLK_CARET);
	lua_rawset(L,-3);
	lua_pushliteral(L,"^");
	lua_rawseti(L,-3,SDLK_CARET);
	// SDLK_COMMA
	lua_pushliteral(L,",");
	lua_pushinteger(L,SDLK_COMMA);
	lua_rawset(L,-3);
	lua_pushliteral(L,",");
	lua_rawseti(L,-3,SDLK_COMMA);
	// SDLK_DOLLAR
	lua_pushliteral(L,"$");
	lua_pushinteger(L,SDLK_DOLLAR);
	lua_rawset(L,-3);
	lua_pushliteral(L,"$");
	lua_rawseti(L,-3,SDLK_DOLLAR);
	// SDLK_EQUALS
	lua_pushliteral(L,"=");
	lua_pushinteger(L,SDLK_EQUALS);
	lua_rawset(L,-3);
	lua_pushliteral(L,"=");
	lua_rawseti(L,-3,SDLK_EQUALS);
	// SDLK_EXCLAIM
	lua_pushliteral(L,"!");
	lua_pushinteger(L,SDLK_EXCLAIM);
	lua_rawset(L,-3);
	lua_pushliteral(L,"!");
	lua_rawseti(L,-3,SDLK_EXCLAIM);
	// SDLK_GREATER
	lua_pushliteral(L,">");
	lua_pushinteger(L,SDLK_GREATER);
	lua_rawset(L,-3);
	lua_pushliteral(L,">");
	lua_rawseti(L,-3,SDLK_GREATER);
	// SDLK_HASH
	lua_pushliteral(L,"#");
	lua_pushinteger(L,SDLK_HASH);
	lua_rawset(L,-3);
	lua_pushliteral(L,"#");
	lua_rawseti(L,-3,SDLK_HASH);
	// SDLK_LEFTBRACKET
	lua_pushliteral(L,"[");
	lua_pushinteger(L,SDLK_LEFTBRACKET);
	lua_rawset(L,-3);
	lua_pushliteral(L,"[");
	lua_rawseti(L,-3,SDLK_LEFTBRACKET);
	// SDLK_LEFTPAREN
	lua_pushliteral(L,"(");
	lua_pushinteger(L,SDLK_LEFTPAREN);
	lua_rawset(L,-3);
	lua_pushliteral(L,"(");
	lua_rawseti(L,-3,SDLK_LEFTPAREN);
	// SDLK_LESS
	lua_pushliteral(L,"<");
	lua_pushinteger(L,SDLK_LESS);
	lua_rawset(L,-3);
	lua_pushliteral(L,"<");
	lua_rawseti(L,-3,SDLK_LESS);
	// SDLK_MINUS
	lua_pushliteral(L,"-");
	lua_pushinteger(L,SDLK_MINUS);
	lua_rawset(L,-3);
	lua_pushliteral(L,"-");
	lua_rawseti(L,-3,SDLK_MINUS);
	// SDLK_PERCENT
	lua_pushliteral(L,"%");
	lua_pushinteger(L,SDLK_PERCENT);
	lua_rawset(L,-3);
	lua_pushliteral(L,"%");
	lua_rawseti(L,-3,SDLK_PERCENT);
	// SDLK_PERIOD
	lua_pushliteral(L,".");
	lua_pushinteger(L,SDLK_PERIOD);
	lua_rawset(L,-3);
	lua_pushliteral(L,".");
	lua_rawseti(L,-3,SDLK_PERIOD);
	// SDLK_PLUS
	lua_pushliteral(L,"+");
	lua_pushinteger(L,SDLK_PLUS);
	lua_rawset(L,-3);
	lua_pushliteral(L,"+");
	lua_rawseti(L,-3,SDLK_PLUS);
	// SDLK_QUESTION
	lua_pushliteral(L,"?");
	lua_pushinteger(L,SDLK_QUESTION);
	lua_rawset(L,-3);
	lua_pushliteral(L,"?");
	lua_rawseti(L,-3,SDLK_QUESTION);
	// SDLK_QUOTE
	lua_pushliteral(L,"'");
	lua_pushinteger(L,SDLK_QUOTE);
	lua_rawset(L,-3);
	lua_pushliteral(L,"'");
	lua_rawseti(L,-3,SDLK_QUOTE);
	// SDLK_QUOTEDBL
	lua_pushliteral(L,"\"");
	lua_pushinteger(L,SDLK_QUOTEDBL);
	lua_rawset(L,-3);
	lua_pushliteral(L,"\"");
	lua_rawseti(L,-3,SDLK_QUOTEDBL);
	// SDLK_RIGHTBRACKET
	lua_pushliteral(L,"]");
	lua_pushinteger(L,SDLK_RIGHTBRACKET);
	lua_rawset(L,-3);
	lua_pushliteral(L,"]");
	lua_rawseti(L,-3,SDLK_RIGHTBRACKET);
	// SDLK_RIGHTPAREN
	lua_pushliteral(L,")");
	lua_pushinteger(L,SDLK_RIGHTPAREN);
	lua_rawset(L,-3);
	lua_pushliteral(L,")");
	lua_rawseti(L,-3,SDLK_RIGHTPAREN);
	// SDLK_SEMICOLON
	lua_pushliteral(L,";");
	lua_pushinteger(L,SDLK_SEMICOLON);
	lua_rawset(L,-3);
	lua_pushliteral(L,";");
	lua_rawseti(L,-3,SDLK_SEMICOLON);
	// SDLK_SLASH
	lua_pushliteral(L,"/");
	lua_pushinteger(L,SDLK_SLASH);
	lua_rawset(L,-3);
	lua_pushliteral(L,"/");
	lua_rawseti(L,-3,SDLK_SLASH);
	// SDLK_UNDERSCORE
	lua_pushliteral(L,"_");
	lua_pushinteger(L,SDLK_UNDERSCORE);
	lua_rawset(L,-3);
	lua_pushliteral(L,"_");
	lua_rawseti(L,-3,SDLK_UNDERSCORE);

	// Nav keys //
	// SDLK_DOWN
	lua_pushliteral(L,"down");
	lua_pushinteger(L,SDLK_DOWN);
	lua_rawset(L,-3);
	lua_pushliteral(L,"down");
	lua_rawseti(L,-3,SDLK_DOWN);
	// SDLK_LEFT
	lua_pushliteral(L,"left");
	lua_pushinteger(L,SDLK_LEFT);
	lua_rawset(L,-3);
	lua_pushliteral(L,"left");
	lua_rawseti(L,-3,SDLK_LEFT);
	// SDLK_RIGHT
	lua_pushliteral(L,"right");
	lua_pushinteger(L,SDLK_RIGHT);
	lua_rawset(L,-3);
	lua_pushliteral(L,"right");
	lua_rawseti(L,-3,SDLK_RIGHT);
	// SDLK_UP
	lua_pushliteral(L,"up");
	lua_pushinteger(L,SDLK_UP);
	lua_rawset(L,-3);
	lua_pushliteral(L,"up");
	lua_rawseti(L,-3,SDLK_UP);
	// SDLK_END
	lua_pushliteral(L,"end");
	lua_pushinteger(L,SDLK_END);
	lua_rawset(L,-3);
	lua_pushliteral(L,"end");
	lua_rawseti(L,-3,SDLK_END);
	// SDLK_HOME
	lua_pushliteral(L,"home");
	lua_pushinteger(L,SDLK_HOME);
	lua_rawset(L,-3);
	lua_pushliteral(L,"home");
	lua_rawseti(L,-3,SDLK_HOME);
	// SDLK_PAGEDOWN
	lua_pushliteral(L,"pagedown");
	lua_pushinteger(L,SDLK_PAGEDOWN);
	lua_rawset(L,-3);
	lua_pushliteral(L,"pagedown");
	lua_rawseti(L,-3,SDLK_PAGEDOWN);
	// SDLK_PAGEUP
	lua_pushliteral(L,"pageup");
	lua_pushinteger(L,SDLK_PAGEUP);
	lua_rawset(L,-3);
	lua_pushliteral(L,"pageup");
	lua_rawseti(L,-3,SDLK_PAGEUP);

	// Editing keys //
	// SDLK_BACKSPACE
	lua_pushliteral(L,"backspace");
	lua_pushinteger(L,SDLK_BACKSPACE);
	lua_rawset(L,-3);
	lua_pushliteral(L,"backspace");
	lua_rawseti(L,-3,SDLK_BACKSPACE);
	// SDLK_CLEAR
	lua_pushliteral(L,"clear");
	lua_pushinteger(L,SDLK_CLEAR);
	lua_rawset(L,-3);
	lua_pushliteral(L,"clear");
	lua_rawseti(L,-3,SDLK_CLEAR);
	// SDLK_DELETE
	lua_pushliteral(L,"delete");
	lua_pushinteger(L,SDLK_DELETE);
	lua_rawset(L,-3);
	lua_pushliteral(L,"delete");
	lua_rawseti(L,-3,SDLK_DELETE);
	// SDLK_INSERT
	lua_pushliteral(L,"insert");
	lua_pushinteger(L,SDLK_INSERT);
	lua_rawset(L,-3);
	lua_pushliteral(L,"insert");
	lua_rawseti(L,-3,SDLK_INSERT);
	// SDLK_RETURN
	lua_pushliteral(L,"return");
	lua_pushinteger(L,SDLK_RETURN);
	lua_rawset(L,-3);
	lua_pushliteral(L,"return");
	lua_rawseti(L,-3,SDLK_RETURN);
	// SDLK_TAB
	lua_pushliteral(L,"tab");
	lua_pushinteger(L,SDLK_TAB);
	lua_rawset(L,-3);
	lua_pushliteral(L,"tab");
	lua_rawseti(L,-3,SDLK_TAB);

	// Modifier keys //
	// SDLK_CAPSLOCK
	lua_pushliteral(L,"capslock");
	lua_pushinteger(L,SDLK_CAPSLOCK);
	lua_rawset(L,-3);
	lua_pushliteral(L,"capslock");
	lua_rawseti(L,-3,SDLK_CAPSLOCK);
	// SDLK_MODE
	lua_pushliteral(L,"mode");
	lua_pushinteger(L,SDLK_MODE);
	lua_rawset(L,-3);
	lua_pushliteral(L,"mode");
	lua_rawseti(L,-3,SDLK_MODE);
	// SDLK_NUMLOCKCLEAR
	lua_pushliteral(L,"numlock");
	lua_pushinteger(L,SDLK_NUMLOCKCLEAR);
	lua_rawset(L,-3);
	lua_pushliteral(L,"numlock");
	lua_rawseti(L,-3,SDLK_NUMLOCKCLEAR);
	// SDLK_SCROLLLOCK
	lua_pushliteral(L,"scrolllock");
	lua_pushinteger(L,SDLK_SCROLLLOCK);
	lua_rawset(L,-3);
	lua_pushliteral(L,"scrolllock");
	lua_rawseti(L,-3,SDLK_SCROLLLOCK);
	// SDLK_LGUI
	lua_pushliteral(L,"lgui");
	lua_pushinteger(L,SDLK_LGUI);
	lua_rawset(L,-3);
	lua_pushliteral(L,"lgui");
	lua_rawseti(L,-3,SDLK_LGUI);
	// SDLK_RGUI
	lua_pushliteral(L,"rgui");
	lua_pushinteger(L,SDLK_RGUI);
	lua_rawset(L,-3);
	lua_pushliteral(L,"rgui");
	lua_rawseti(L,-3,SDLK_RGUI);
	// SDLK_LSHIFT
	lua_pushliteral(L,"lshift");
	lua_pushinteger(L,SDLK_LSHIFT);
	lua_rawset(L,-3);
	lua_pushliteral(L,"lshift");
	lua_rawseti(L,-3,SDLK_LSHIFT);
	// SDLK_RSHIFT
	lua_pushliteral(L,"rshift");
	lua_pushinteger(L,SDLK_RSHIFT);
	lua_rawset(L,-3);
	lua_pushliteral(L,"rshift");
	lua_rawseti(L,-3,SDLK_RSHIFT);
	// SDLK_LALT
	lua_pushliteral(L,"lalt");
	lua_pushinteger(L,SDLK_LALT);
	lua_rawset(L,-3);
	lua_pushliteral(L,"lalt");
	lua_rawseti(L,-3,SDLK_LALT);
	// SDLK_RALT
	lua_pushliteral(L,"ralt");
	lua_pushinteger(L,SDLK_RALT);
	lua_rawset(L,-3);
	lua_pushliteral(L,"ralt");
	lua_rawseti(L,-3,SDLK_RALT);
	// SDLK_LCTRL
	lua_pushliteral(L,"lctrl");
	lua_pushinteger(L,SDLK_LCTRL);
	lua_rawset(L,-3);
	lua_pushliteral(L,"lctrl");
	lua_rawseti(L,-3,SDLK_LCTRL);
	// SDLK_RCTRL
	lua_pushliteral(L,"rctrl");
	lua_pushinteger(L,SDLK_RCTRL);
	lua_rawset(L,-3);
	lua_pushliteral(L,"rctrl");
	lua_rawseti(L,-3,SDLK_RCTRL);

	// misc keys //
	// SDLK_PAUSE
	lua_pushliteral(L,"pause");
	lua_pushinteger(L,SDLK_PAUSE);
	lua_rawset(L,-3);
	lua_pushliteral(L,"pause");
	lua_rawseti(L,-3,SDLK_PAUSE);
	// SDLK_ESCAPE
	lua_pushliteral(L,"escape");
	lua_pushinteger(L,SDLK_ESCAPE);
	lua_rawset(L,-3);
	lua_pushliteral(L,"escape");
	lua_rawseti(L,-3,SDLK_ESCAPE);
	// SDLK_HELP
	lua_pushliteral(L,"help");
	lua_pushinteger(L,SDLK_HELP);
	lua_rawset(L,-3);
	lua_pushliteral(L,"help");
	lua_rawseti(L,-3,SDLK_HELP);
	// SDLK_MENU
	lua_pushliteral(L,"menu");
	lua_pushinteger(L,SDLK_MENU);
	lua_rawset(L,-3);
	lua_pushliteral(L,"menu");
	lua_rawseti(L,-3,SDLK_MENU);
	// SDLK_PRINTSCREEN
	lua_pushliteral(L,"printscreen");
	lua_pushinteger(L,SDLK_PRINTSCREEN);
	lua_rawset(L,-3);
	lua_pushliteral(L,"printscreen");
	lua_rawseti(L,-3,SDLK_PRINTSCREEN);
	// SDLK_SYSREQ
	lua_pushliteral(L,"sysreq");
	lua_pushinteger(L,SDLK_SYSREQ);
	lua_rawset(L,-3);
	lua_pushliteral(L,"sysreq");
	lua_rawseti(L,-3,SDLK_SYSREQ);
	// SDLK_APPLICATION
	lua_pushliteral(L,"application");
	lua_pushinteger(L,SDLK_APPLICATION);
	lua_rawset(L,-3);
	lua_pushliteral(L,"application");
	lua_rawseti(L,-3,SDLK_APPLICATION);
	// SDLK_POWER
	lua_pushliteral(L,"power");
	lua_pushinteger(L,SDLK_POWER);
	lua_rawset(L,-3);
	lua_pushliteral(L,"power");
	lua_rawseti(L,-3,SDLK_POWER);
	// SDLK_CURRENCYUNIT
	lua_pushliteral(L,"currencyunit");
	lua_pushinteger(L,SDLK_CURRENCYUNIT);
	lua_rawset(L,-3);
	lua_pushliteral(L,"currencyunit");
	lua_rawseti(L,-3,SDLK_CURRENCYUNIT);
	// SDLK_UNDO
	lua_pushliteral(L,"undo");
	lua_pushinteger(L,SDLK_UNDO);
	lua_rawset(L,-3);
	lua_pushliteral(L,"undo");
	lua_rawseti(L,-3,SDLK_UNDO);

#endif